// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjmyzzijgwgxywvgfihu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqbXl6emlqZ3dneHl3dmdmaWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0Njg0ODgsImV4cCI6MjA1MTA0NDQ4OH0.op3gm7fwjITAUhcvtlI06WCC84d0tgvlWPUURHcSaKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);